# URL do bucket S3 criado pelo CloudFormation
# Nome fixo do bucket definido no template: my-s3-books-cloudformation-test
# Região padrão: us-east-1
s3.url=https://my-s3-books-cloudformation-test.s3.us-east-1.amazonaws.com

# Nome da tabela DynamoDB criada pelo CloudFormation
# Este valor é fixo e definido no template CloudFormation (TableName: books)
dynamodb.table.books=books
