AWSTemplateFormatVersion: "2010-09-09"
Description: "Template principal para orquestrar a infraestrutura do cenário de livros"

Parameters:
  TemplatesBucketName:
    Type: String
    Description: Nome do bucket S3 onde os templates das stacks filhas estão armazenados

  DynamoDbTemplateKey:
    Type: String
    Default: dynamodb/books.yaml
    Description: Caminho (key) do template da stack de DynamoDB dentro do bucket de templates

  S3TemplateKey:
    Type: String
    Default: s3_bucket/bookStorage.yaml
    Description: Caminho (key) do template da stack de S3 dentro do bucket de templates

  LambdaTemplateKey:
    Type: String
    Default: lambda/booksEtl.yaml
    Description: Caminho (key) do template da stack de Lambda dentro do bucket de templates

  BooksTableName:
    Type: String
    Default: books
    Description: Nome da tabela DynamoDB

  BookStorageBucketName:
    Type: String
    Default: bookstorage
    Description: Nome do bucket S3 de armazenamento dos livros

  BooksLambdaFunctionName:
    Type: String
    Default: booksEtl
    Description: Nome da função Lambda de ETL dos livros

  BooksLambdaCodeBucket:
    Type: String
    Description: Nome do bucket S3 que armazena o artefato (código) da função Lambda

  BooksLambdaCodeKey:
    Type: String
    Default: booksEtl.jar
    Description: Caminho (key) do artefato da função Lambda dentro do bucket informado

  BooksLambdaHandler:
    Type: String
    Default: com.example.BooksEtlHandler::handleRequest
    Description: Handler da função Lambda (classe::metodo)

  BooksLambdaTimeout:
    Type: Number
    Default: 30
    MinValue: 1
    MaxValue: 900
    Description: Timeout da função Lambda em segundos

  BooksLambdaMemorySize:
    Type: Number
    Default: 512
    Description: Memória (em MB) alocada para a função Lambda

Resources:
  BooksDynamoDbStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.${AWS::Region}.amazonaws.com/${DynamoDbTemplateKey}
      Parameters:
        TableName: !Ref BooksTableName

  BookStorageS3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.${AWS::Region}.amazonaws.com/${S3TemplateKey}
      Parameters:
        BucketName: !Ref BookStorageBucketName

  BooksLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.${AWS::Region}.amazonaws.com/${LambdaTemplateKey}
      Parameters:
        FunctionName: !Ref BooksLambdaFunctionName
        S3Bucket: !Ref BooksLambdaCodeBucket
        S3Key: !Ref BooksLambdaCodeKey
        Handler: !Ref BooksLambdaHandler
        Timeout: !Ref BooksLambdaTimeout
        MemorySize: !Ref BooksLambdaMemorySize

Outputs:
  DynamoDbTableName:
    Description: Nome da tabela DynamoDB criada pela stack filha
    Value: !GetAtt BooksDynamoDbStack.Outputs.TableName
    Export:
      Name: !Sub ${AWS::StackName}-DynamoDbTableName

  DynamoDbTableArn:
    Description: ARN da tabela DynamoDB criada pela stack filha
    Value: !GetAtt BooksDynamoDbStack.Outputs.TableArn
    Export:
      Name: !Sub ${AWS::StackName}-DynamoDbTableArn

  DynamoDbTableStreamArn:
    Description: ARN do stream da tabela DynamoDB criada pela stack filha
    Value: !GetAtt BooksDynamoDbStack.Outputs.TableStreamArn
    Export:
      Name: !Sub ${AWS::StackName}-DynamoDbTableStreamArn

  BookStorageBucketNameOutput:
    Description: Nome do bucket S3 criado pela stack filha
    Value: !GetAtt BookStorageS3Stack.Outputs.BucketName
    Export:
      Name: !Sub ${AWS::StackName}-BookStorageBucketName

  BookStorageBucketArn:
    Description: ARN do bucket S3 criado pela stack filha
    Value: !GetAtt BookStorageS3Stack.Outputs.BucketArn
    Export:
      Name: !Sub ${AWS::StackName}-BookStorageBucketArn

  BookStorageBucketDomainName:
    Description: Nome de domínio do bucket S3 criado pela stack filha
    Value: !GetAtt BookStorageS3Stack.Outputs.BucketDomainName
    Export:
      Name: !Sub ${AWS::StackName}-BookStorageBucketDomainName

  BooksLambdaFunctionNameOutput:
    Description: Nome da função Lambda criada pela stack filha
    Value: !GetAtt BooksLambdaStack.Outputs.FunctionName
    Export:
      Name: !Sub ${AWS::StackName}-BooksLambdaFunctionName

  BooksLambdaFunctionArn:
    Description: ARN da função Lambda criada pela stack filha
    Value: !GetAtt BooksLambdaStack.Outputs.FunctionArn
    Export:
      Name: !Sub ${AWS::StackName}-BooksLambdaFunctionArn

  BooksLambdaExecutionRoleArn:
    Description: ARN da role de execução da função Lambda criada pela stack filha
    Value: !GetAtt BooksLambdaStack.Outputs.FunctionRoleArn
    Export:
      Name: !Sub ${AWS::StackName}-BooksLambdaExecutionRoleArn

