AWSTemplateFormatVersion: "2010-09-09"
Description: Template para criação da tabela DynamoDB books

Parameters:
  TableName:
    Type: String
    Default: books
    Description: Nome da tabela DynamoDB
    ConstraintDescription: O nome da tabela deve seguir as regras de nomenclatura do DynamoDB

Resources:
  BooksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: autor
          AttributeType: S
        - AttributeName: genero
          AttributeType: S
      KeySchema:
        - AttributeName: autor
          KeyType: HASH
        - AttributeName: genero
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  TableName:
    Description: Nome da tabela DynamoDB criada
    Value: !Ref BooksTable
    Export:
      Name: !Sub ${AWS::StackName}-TableName

  TableArn:
    Description: ARN da tabela DynamoDB
    Value: !GetAtt BooksTable.Arn
    Export:
      Name: !Sub ${AWS::StackName}-TableArn

  TableStreamArn:
    Description: ARN do stream da tabela DynamoDB
    Value: !GetAtt BooksTable.StreamArn
    Export:
      Name: !Sub ${AWS::StackName}-TableStreamArn
